MULTI_EXTR_FEW_SHOTS = [
    ("source_question: Who was the first to visit France after the Royal Administration of Wallis and Futuna?", {"anchor_triples": [["Royal Administration of Wallis and Futuna", "visit", "France"]], "search_triple": ["?", "visit", "France"]}),
    ("source_question: Who used conventional military force against Iraq on 23 June 2007?", {"anchor_triples": [], "search_triple": ["?", "used conventional military force", "Iraq"]}),
    ("source_question: Which country did Colombia negotiate with in the same year as Japan?", {"anchor_triples": [["Colombia", "negotiate with", "Japan"]], "search_triple": ["Colombia", "negotiate with", "?"]}),
    ("source_question: Before Oct 2005, with which country did Oman sign an agreement?", {"anchor_triples": [], "search_triple": ["Oman", "sign an agreement", "?"]}),
    ("source_question: In which month did the Philippine police first use conventional military force against Malaysia?", {"anchor_triples": [["Philippine police", "use conventional military force against", "Malaysia"]], "search_triple": None}),
    ("source_question: When did Oman visit Islam Karimov?", {"anchor_triples": [["Oman", "visit", "Islam Karimov"]], "search_triple": None}),
    ("source_question: Before the Iraqi interim government, which country was last negotiated with by China?", {"anchor_triples": [["China", "negotiate with", "Iraqi interim government"]], "search_triple": ["China", "negotiate with", "?"]}),
    ("source_question: Who was accused by Zawahiri after 2005?", {"anchor_triples": [], "search_triple": ["Zawahiri", "accuse", "?"]}),
]

CORN_EXTR_FEW_SHOTS = [
    ("source_question: How many days did Adrian Vale serve as a member of the Northbridge City Council?", {"anchor_triples": [["Adrian Vale", "as a member of", " the Northbridge City Council"]], "search_triple": None}),
    ("source_question: When did Helena Marwick finish her term as the Governor of Eastmere?", {"anchor_triples": [["Helena Marwick", "term as", "Governor of Eastmere"]], "search_triple": None}),
    ("source_question: When did Celia Morren win the Meridian Screenwriting Prize?", {"anchor_triples": ["Meridian Screenwriting Prize", "winner", "Celia Morren"], "search_triple": None}),
    ("source_question: Who received the Aurora Literary Medal on 2006-01-01?", {"anchor_triples": [], "search_triple": ["?", "award received", "Aurora Literary Medal"]}),
    ("source_question: What significant event occurred for Lucien Marot on 1994-01-01?", {"anchor_triples": [], "search_triple": ["Lucien Marot", "significant event", "?"]}),
    ("source_question: What are the combined time periods for when Clara Voss was chairperson of the Collegiate Civic Union and when Mateo Rinaldi was a member of the Norbridge national football team?", {"anchor_triples": [["Collegiate Civic Union", "chairperson", "Clara Voss"], ["Mateo Rinaldi", "a member of team", "Norbridge national football"]], "search_triple": None}),
    ("source_question: Who received the Lyran Cultural Distinction 20,820 days after the 1932 Meridian Games and 13,149 days after Elias Koren won the Helios Medal?", {"anchor_triples": [["1932 Meridian Games", "significant event", "occurrence"], ["Helios Medal", "winner", "Elias Koren"]], "search_triple": ["?", "award received", "Lyran Cultural Distinction"]}),
    ("source_question: Based on their end times, what is the chronological rank of the event involving Nora Dalca among the following events: Nora Dalca's position as Provincial Assembly Delegate, Malcolm Redd's position as Governor of Westhaven, and Elena Moroz's receipt of the Crescent Research Medal?", {"anchor_triples": [["Nora Dalca", "position held", "Provincial Assembly Delegate"], ["Malcolm Redd", "position held", "Governor of Westhaven"], ["Elena Moroz", "award received", "Crescent Research Medal"]], "search_triple": None}),
    ("source_question: Among Liora Mendel's residency at the Arcadian Academy, Thomas Wycliffe's tenure as Leader of the Opposition, and Sabine Keller's time as a member of the Federal Assembly, which event had the 2nd longest duration?", {"anchor_triples": [["Liora Mendel", "residency at", "Arcadian Academy"], ["Thomas Wycliffe", "tenure as", "Leader of the Opposition"], ["Sabine Keller", "as amember of", "Federal Assembly"]], "search_triple": None}),
]

ENTITY_ALIGN_FEW_SHOTS = [
    ({"original_question": "Which country was the first to negotiate with Thailand after Donald Rumsfeld?", "gold": {"triples": [["Donald Rumsfeld", "Engage in negotiation", "Thailand"], ["China", "Engage in negotiation", "Thailand"], ["Cambodia", "Visit", "Thailand"]], "entities": ["Donald Rumsfeld", "Thailand", "China", "Cambodia"], "relations": ["Engage in negotiation", "Express intent to meet or negotiate", "Visit"]}, "source_triples": {"anchor_triples": [["Donald Rumsfeld", "negotiate with", "Thailand"]], "search_triple": ["?", "negotiate with", "Thailand"]}}, {"grounded_triples": {"anchor_triples": [["Donald Rumsfeld", "Engage in negotiation", "Thailand"]], "search_triple": ["?", "Engage in negotiation", "Thailand"]}}),
    ({"original_question": "Before James Kabarebe, who was the last to want to meet with Burundi?", "gold": {"triples": [["James Kabarebe", "Express intent to meet or negotiate", "Burundi"], ["China", "Express intent to meet or negotiate", "Burundi"], ["China", "Engage in negotiation", "Burundi"]], "entities": ["James Kabarebe", "Burundi", "China"], "relations": ["Express intent to meet or negotiate", "Engage in negotiation", "Visit"]}, "source_triples": {"anchor_triples": [["James Kabarebe", "want to meet with", "Burundi"]], "search_triple": ["?", "want to meet with", "Burundi"]}}, {"grounded_triples": {"anchor_triples": [["James Kabarebe", "Express intent to meet or negotiate", "Burundi"]], "search_triple": ["?", "Express intent to meet or negotiate", "Burundi"]}}),
    ({"original_question": "After Malaysia, who received the visit from Mswati III first?", "gold": {"triples": [["Mswati III", "Make a visit", "Malaysia"], ["Mswati III", "Make a visit", "Jakaya Mrisho Kikwete"], ["China", "Host a visit", "Mswati III"]], "entities": ["Malaysia", "China", "Mswati III"], "relations": ["Receive visit", "Visit", "Engage in negotiation"]}, "source_triples": {"anchor_triples": [["Mswati", "visit", "Malaysia"]], "search_triple": ["Mswati III", "visit", "?"]}}, {"grounded_triples": {"anchor_triples": [["Mswati III", "Make a visit", "Malaysia"]], "search_triple": ["Mswati III", "Make a visit", "?"]}}),
    ({"original_question": "After China, who was the first to praise the leader of South Korea?", "gold": {"triples": [["China", "Praise or endorse", "Head of Government (South Korea)"], ["Japan", "Praise or endorse", "Head of Government (South Korea)"], ["China", "Criticize or denounce", "Head of Government (South Korea)"]], "entities": ["China", "Japan", "Head of Government (South Korea)", "Government (South Korea)"], "relations": ["Praise or endorse", "Criticize or denounce", "Make a statement"]}, "source_triples": {"anchor_triples": [["China", "praise", "the leader of South Korea"]], "search_triple": ["?", "praise", "the leader of South Korea"]}}, {"grounded_triples": {"anchor_triples": [["China", "Praise or endorse", "Head of Government (South Korea)"]], "search_triple": ["?", "Praise or endorse", "Head of Government (South Korea)"]}}),
    ({"original_question": "Before the government of Sudan, who was the last to criticise Ethiopia?", "gold": {"triples": [["Government (Sudan)", "Criticize or denounce", "Ethiopia"], ["China", "Criticize or denounce", "Ethiopia"], ["Government (Sudan)", "Make a statement", "Ethiopia"]], "entities": ["Government (Sudan)", "China", "Ethiopia", "Media (Sudan)"], "relations": ["Criticize or denounce", "Make a statement", "Praise or endorse"]}, "source_triples": {"anchor_triples": [["the government of Sudan", "criticise", "Ethiopia"]], "search_triple": ["?", "criticise", "Ethiopia"]}}, {"grounded_triples": {"anchor_triples": [["Government (Sudan)", "Criticize or denounce", "Ethiopia"]], "search_triple": ["?", "Criticize or denounce", "Ethiopia"]}}),
    ({"original_question": "Who made the first request to China after the lawyer/attorney of the United States?", "gold": {"triples": [["Lawyer/Attorney (United States)", "Make an appeal or request", "China"], ["Barack Obama", "Make an appeal or request", "China"], ["Lawyer/Attorney (United States)", "Make a statement", "China"]], "entities": ["Lawyer/Attorney (United States)", "Barack Obama", "China", "Citizen (United States)"], "relations": ["Make an appeal or request", "Make a statement", "Criticize or denounce"]}, "source_triples": {"anchor_triples": [["the lawyer/attorney of the United States", "request", "China"]], "search_triple": ["?", "request", "China"]}}, {"grounded_triples": {"anchor_triples": [["Lawyer/Attorney (United States)", "Make an appeal or request", "China"]], "search_triple": ["?", "Make an appeal or request", "China"]}}),
    ({"original_question": "Could you tell me the exact month when China signed formal agreements with the US Department of Energy?", "gold": {"triples": [["China", "Sign formal agreement", "Department of Energy (United States)"], ["China", "Engage in negotiation", "Department of Energy (United States)"], ["China", "Visit", "Department of Energy (United States)"]], "entities": ["China", "Department of Energy (United States)", "US Department of Defense"], "relations": ["Sign formal agreement", "Engage in negotiation", "Visit"]}, "source_triples": {"anchor_triples": [["China", "signed formal agreements with", "the US Department of Energy"]], "search_triple": None}}, {"grounded_triples": {"anchor_triples": [["China", "Sign formal agreement", "Department of Energy (United States)"]], "search_triple": None}}),
]

TEMPORAL_CONSTRAINT_FEW_SHOTS = [
    ({"question": "On 27 October 2006, which country signed formal agreements with China?", "decomposed_triples": {"anchor_triples": [], "search_triple": ["?", "sign formal agreements with", "China"]}}, {"constraints": [{"anchor_kind": "explicit_time", "relation": "equal", "anchor_index": None, "time_text": "27 October 2006", "interval_start": None, "interval_end": None, "granularity": "day", "offset_days": None}], "ranking": None}),
    ({"question": "In Apr 2011, which country recommended Burundi?", "decomposed_triples": {"anchor_triples": [], "search_triple": ["?", "recommend", "Burundi"]}}, {"constraints": [{"anchor_kind": "explicit_time", "relation": "equal", "anchor_index": None, "time_text": "Apr 2011", "interval_start": None, "interval_end": None, "granularity": "month", "offset_days": None}], "ranking": None}),
    ({"question": "Before 15 April 2005, which country did Iraq declare its intention to meet?", "decomposed_triples": {"anchor_triples": [], "search_triple": ["Iraq", "declare its intention to meet", "?"]}}, {"constraints": [{"anchor_kind": "explicit_time", "relation": "before", "anchor_index": None, "time_text": "15 April 2005", "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}], "ranking": None}),
    ({"question": "After Oman, which country received the visit from Sheikh Ahmed Abdullah first?", "decomposed_triples": {"anchor_triples": [["Oman", "receive the visit from", "Sheikh Ahmed Abdullah"]], "search_triple": ["?", "receive the visit from", "Sheikh Ahmed Abdullah"]}}, {"constraints": [{"anchor_kind": "event", "relation": "after", "anchor_index": 0, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}], "ranking": {"rank": "asc", "rank_k": 1}}),
    ({"question": "Which country was the last to sign formal agreements with Malaysia before the armed rebels of Ukraine did so?", "decomposed_triples": {"anchor_triples": [["armed rebels of Ukraine", "sign formal agreements with", "Malaysia"]], "search_triple": ["?", "sign formal agreements with", "Malaysia"]}}, {"constraints": [{"anchor_kind": "event", "relation": "before", "anchor_index": 0, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}], "ranking": {"rank": "desc", "rank_k": 1}}),
    ({"question": "Who made optimistic comments about China in the same month as Eric Chu?", "decomposed_triples": {"anchor_triples": [["Eric Chu", "make optimistic comments about", "China"]], "search_triple": ["?", "make optimistic comments about", "China"]}}, {"constraints": [{"anchor_kind": "event", "relation": "equal", "anchor_index": 0, "time_text": None, "interval_start": None, "interval_end": None, "granularity": "month", "offset_days": None}], "ranking": None}),
    ({"question": "Which sports team did Mark Hilditch play for between 1977 and 1983?", "decomposed_triples": {"anchor_triples": [], "search_triple": ["Mark Hilditch", "member of sports team", "?"]}}, {"constraints": [{"anchor_kind": "explicit_interval", "relation": "inside", "anchor_index": None, "time_text": None, "interval_start": "1977", "interval_end": "1983", "granularity": None, "offset_days": None}], "ranking": None}),
    ({"question": "Which individuals were awarded the Order of Bogdan Khmelnitsky, 1st class on January 1, 1944?", "decomposed_triples": {"anchor_triples": [], "search_triple": ["?", "award received", "Order of Bogdan Khmelnitsky, 1st class"]}}, {"constraints": [{"anchor_kind": "explicit_time", "relation": "equal", "anchor_index": None, "time_text": "January 1, 1944", "interval_start": None, "interval_end": None, "granularity": "day", "offset_days": None}], "ranking": None}),
    ({"question": "Which award did Erich Fried receive on January 1, 1986?", "decomposed_triples": {"anchor_triples": [], "search_triple": ["Erich Fried", "award received", "?"]}}, {"constraints": [{"anchor_kind": "explicit_time", "relation": "equal", "anchor_index": None, "time_text": "January 1, 1986", "interval_start": None, "interval_end": None, "granularity": "day", "offset_days": None}], "ranking": None}),
    ({"question": "Which sports teams did Nelson Vivas play for after Sydney Chapman received the De Morgan Medal and after Massimo Gallaccio's time with Torino Football Club?", "decomposed_triples": {"anchor_triples": [["Sydney Chapman", "award received", "De Morgan Medal"], ["Massimo Gallaccio", "member of sports team", "Torino Football Club"]], "search_triple": ["Nelson Vivas", "member of sports team", "?"]}}, {"constraints": [{"anchor_kind": "event", "relation": "after", "anchor_index": 0, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}, {"anchor_kind": "event", "relation": "after", "anchor_index": 1, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}], "ranking": None}),
    ({"question": "Before Brett Williams joined Stoke City F.C. and before Luca Toni played for Unione Sportiva Città di Palermo, which sports teams did Jack Ranson play for?", "decomposed_triples": {"anchor_triples": [["Brett Williams", "member of sports team", "Stoke City F.C."], ["Luca Toni", "member of sports team", "Unione Sportiva Città di Palermo"]], "search_triple": ["Jack Ranson", "member of sports team", "?"]}}, {"constraints": [{"anchor_kind": "event", "relation": "before", "anchor_index": 0, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}, {"anchor_kind": "event", "relation": "before", "anchor_index": 1, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": None}], "ranking": None}),
    ({"question": "Which awards did Rolf de Heer win 7305 days after Wilf Smith's time with Brighton & Hove Albion F.C. and 9862 days after Nikolai Bogolyubov received the Order of Lenin?", "decomposed_triples": {"anchor_triples": [["Wilf Smith", "member of sports team", "Brighton & Hove Albion F.C."], ["Nikolai Bogolyubov", "award received", "Order of Lenin"]], "search_triple": ["Rolf de Heer", "winner", "?"]}}, {"constraints": [{"anchor_kind": "event", "relation": "after", "anchor_index": 0, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": 7305}, {"anchor_kind": "event", "relation": "after", "anchor_index": 1, "time_text": None, "interval_start": None, "interval_end": None, "granularity": None, "offset_days": 9862}], "ranking": None}),
]

# QA
MULTI_QA = [
    ({"question": "When did Qatar pay a visit to Barack Obama?", "answer_context": {"temporal_anchor": ["[Qatar, Make a visit, Barack Obama] on 2013-04-23"], "temporal_search": []}}, {"thought": "The context contains one relevant fact: Qatar paid a visit to Barack Obama on 2013-04-23.", "answer": ["2013-04-23"]}),
    ({"question": "When was the last time Hashim Thaçi spoke optimistically about Japan?", "answer_context": {"temporal_anchor": ["[Hashim Thaçi, Make optimistic comment, Japan] on 2012-06-08", "[Hashim Thaçi, Make optimistic comment, Japan] on 2008-03-18"], "temporal_search": []}}, {"thought": "There are two relevant dates, 2008-03-18 and 2012-06-08. The last time is 2012-06-08.", "answer": ["2012-06-08"]}),
    ({"question": "In May 2009, who signed an agreement with Iran?", "answer_context": {"temporal_anchor": [], "temporal_search": ["[Business (Germany), Sign formal agreement, Iran] on 2009-05-27", "[China, Sign formal agreement, Iran] on 2009-05-11", "[Iraq, Sign formal agreement, Iran] on 2009-05-20", "[Tanzania, Sign formal agreement, Iran] on 2009-05-12"]}}, {"thought": "All four candidate facts happened in 2009-05, so the matching entities are Business (Germany), China, Iraq, and Tanzania.", "answer": ["Business (Germany)", "China", "Iraq", "Tanzania"]}),
    ({"question": "Before 14 October 2015, who made Burundi suffer from conventional military forces?", "answer_context": {"temporal_anchor": [], "temporal_search": ["[Al-Shabaab, Use conventional military force, Burundi] on 2015-08-07", "[Al-Shabaab, Use conventional military force, Burundi] on 2013-01-17", "[Military (Burundi), Use conventional military force, Burundi] on 2006-04-30"]}}, {"thought": "All listed candidate facts happened before 2015-10-14, so the matching entities are Al-Shabaab and Military (Burundi).", "answer": ["Al-Shabaab", "Military (Burundi)"]}),
    ({"question": "Could you tell me the exact month when Dmitry Anatolyevich Medvedev requested France?", "answer_context": {"temporal_anchor": ["[Dmitry Anatolyevich Medvedev, Make an appeal or request, France] on 2008-08-14"], "temporal_search": []}}, {"thought": "The only relevant fact is on 2008-08-14. Since the question asks for the exact month, the answer is 2008-08.", "answer": ["2008-08"]}),
    ({"question": "In which year did Abhisit Vejjajiva visit Qatar for the first time?", "answer_context": {"temporal_anchor": ["[Abhisit Vejjajiva, Visit, Qatar] on 2011-05-14", "[Abhisit Vejjajiva, Visit, Qatar] on 2013-08-22"], "temporal_search": []}}, {"thought": "There are two visit records, in 2011 and 2013. The first time is 2011-05-14, so the year is 2011.", "answer": ["2011"]}),
    ({"question": "Who praised Iran in the same month as Nacer Mehal?", "answer_context": {"temporal_anchor": ["[Nacer Mehal, Praise, Iran] on 2010-07-09"], "temporal_search": ["[Algeria, Praise, Iran] on 2010-07-21", "[Syria, Praise, Iran] on 2010-07-03", "[France, Praise, Iran] on 2010-08-02"]}}, {"thought": "Nacer Mehal praised Iran in 2010-07. Among the candidate facts, Algeria and Syria also praised Iran in the same month, while France did so in 2010-08.", "answer": ["Algeria", "Syria"]}),
]

CORN_QA = [
    ({"question": "How long did Adrian Vale serve as a member of the Harbor City F.C.?", "answer_context": {"temporal_anchor": ["[Adrian Vale, member of sports team, Harbor City F.C.] from 2001-01-01 to 2003-01-01"], "temporal_search": []}}, {"thought": "The interval 2001-01-01 to 2003-01-01 spans 2 years with no leap days in between and is calculated exclusively of the end date, resulting in 730 days.", "answer": ["730 days"]}),
    ({"question": "When did Helena Marwick's service as Governor of Eastmere end?", "answer_context": {"temporal_anchor": ["[Helena Marwick, position held, Governor of Eastmere] from 1998-01-01 to 2001-01-01", "[Helena Marwick, position held, Governor of Eastmere] from 2004-01-01 to 2006-01-01"], "temporal_search": []}}, {"thought": "The question asks for the ending dates of the matching service periods. There are two matching intervals, so return both end dates.", "answer": ["2001-01-01", "2006-01-01"]}),
    ({"question": "When did the occurrence of the 2012 Meridian Games end?", "answer_context": {"temporal_anchor": ["[2012 Meridian Games, significant event, occurrence] on 2012-01-01"], "temporal_search": []}}, {"thought": "This is a point event recorded on 2012-01-01. For a point event, the end date is the same as the event date.", "answer": ["2012-01-01"]}),
    ({"question": "Who was a member of Redfield Town F.C. from 2001-01-01 to 2003-01-01?", "answer_context": {"temporal_anchor": [], "temporal_search": ["[Evan Bristow, member of sports team, Redfield Town F.C.] from 2001-01-01 to 2003-01-01", "[Liam Forsyth, member of sports team, Redfield Town F.C.] from 2002-01-01 to 2003-01-01", "[Noah Kendal, member of sports team, Redfield Town F.C.] from 2000-01-01 to 2004-01-01"]}}, {"thought": "The question asks for membership over the exact interval 2001-01-01 to 2003-01-01. Only Evan Bristow matches that full requested period exactly.", "answer": ["Evan Bristow"]}),
    ({"question": "During which periods was Theo Mercer a member of Harbor City F.C.?", "answer_context": {"temporal_anchor": ["[Theo Mercer, member of sports team, Harbor City F.C.] on 2008-01-01", "[Theo Mercer, member of sports team, Harbor City F.C.] from 2010-01-01 to 2012-01-01", "[Theo Mercer, member of sports team, Harbor City F.C.] from 2012-01-01 to 2015-01-01"], "temporal_search": []}}, {"thought": "The question asks for the individual time periods of the fully specified membership event. Return each period separately. A point event is formatted as date to date, and adjacent intervals are not merged because no union operation is requested.", "answer": ["2008-01-01 to 2008-01-01", "2010-01-01 to 2012-01-01", "2012-01-01 to 2015-01-01"]}),
    ({"question": "What are the combined time periods covered by Mira Donnelly's tenure with Westport F.C. and the 2004 Solstice Games occurrence event?", "answer_context": {"temporal_anchor": ["[Mira Donnelly, member of sports team, Westport F.C.] from 1930-01-01 to 1931-01-01", "[2004 Solstice Games, significant event, occurrence] on 2004-01-01"], "temporal_search": []}}, {"thought": "This is a union question over two non-overlapping periods. The point event must be preserved and formatted as a date-to-date interval.", "answer": ["1930-01-01 to 1931-01-01", "2004-01-01 to 2004-01-01"]}),
    ({"question": "Based on their end times, what is the chronological rank of the event involving Nora Dalca among the following events: Nora Dalca's position as Provincial Assembly Delegate, Malcolm Redd's position as Governor of Westhaven, and Elena Moroz's receipt of the Crescent Research Medal?", "answer_context": {"temporal_anchor": ["[Nora Dalca, position held, Provincial Assembly Delegate] from 2001-01-01 to 2004-01-01", "[Malcolm Redd, position held, Governor of Westhaven] from 1998-01-01 to 2001-01-01", "[Elena Moroz, award received, Crescent Research Medal] on 2002-01-01"], "temporal_search": []}}, {"thought": "Sorting by end time gives Malcolm Redd first at 2001-01-01, Elena Moroz second at 2002-01-01, and Nora Dalca third at 2004-01-01. Therefore, Nora Dalca ranks third.", "answer": ["3"]}),
    ({"question": "What is the average duration of Liora Mendel's residency at the Arcadian Academy, Julian Kersey's receipt of the Solis Medal, and Mirela Voss's receipt of the Northern Arts Prize?", "answer_context": {"temporal_anchor": ["[Liora Mendel, residency at, Arcadian Academy] from 2001-01-01 to 2003-01-01", "[Julian Kersey, award received, Solis Medal] on 1998-01-01", "[Mirela Voss, award received, Northern Arts Prize] on 2006-01-01"], "temporal_search": []}}, {"thought": "The three durations are 730 days, 0 days, and 0 days. Their average is 243.33 days, so return 243 days under the dataset's integer-day answer format.", "answer": ["243 days"]}),
]